version: '3.9'
services:
  gitlab-adapter:
    image: ghcr.io/ai-lenok/gitlab-adapter:main
    ports:
      - "8080:8080"
    volumes:
      - ./config/:/app/config/
    environment:
      GA_GITLAB_HOST: "https://gitlab.com"
      GA_GITLAB_TOKEN: "change-me"
