kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: gitlab-adapter-ingress
  labels:
    app: addressbook
spec:
  rules:
    - host: gitlab-adapter.{{ HOST }}
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: gitlab-adapter
                port:
                  name: adapter-api